#!/usr/bin/env python

# facili - easy info tool framework

# Copyright (C) 2018 Siddharudh P T

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 2.1 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.

# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>


from bottle import route, view, request, response, static_file, template, run
import bottle
from facili import get_data, list_plugins


bottle.TEMPLATE_PATH = ['../web/templates']

@route('/data')
def serve_data():
    k = request.query.get('k')
    keys = k.split(',') if k else [] 
    return get_data(keys)


@route('/static/<path:path>')
def  serve_static_content(path):
    return static_file(path, root='../web/static')


@route('/')
@view('index')
def serve_view():
    return {'plugins': list_plugins()}


run(host='0.0.0.0', port=8888, server='twisted')
